apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
type: Opaque
data:
    grafana-username: YWRtaW4= # admin / this is taken by running echo -n admin | base64
    grafana-password: Z3JhZmFuYQ== # grafana / this is taken by running echo -n secret | base64